Tests:
    while(1) :
        plane_0.turn_Off_One_Light()
        plane_0.turn_On_One_Light(0, "RED")
        wait(.1)
        plane_0.turn_On_One_Light(1, "RED")
        plane_0.turn_Off_One_Light(0)
        wait(.1)
        plane_0.turn_On_One_Light(3, "RED")
        plane_0.turn_Off_One_Light(1)
        wait(.1)
        plane_0.turn_On_One_Light(2, "RED")
        plane_0.turn_Off_One_Light(3)
        wait(.1)
        
        plane_0.turn_On_One_Light(0, "GREEN")
        plane_0.turn_Off_One_Light(2)
        wait(.1)
        plane_0.turn_On_One_Light(1, "GREEN")
        plane_0.turn_Off_One_Light(0)
        wait(.1)
        plane_0.turn_On_One_Light(3, "GREEN")
        plane_0.turn_Off_One_Light(1)
        wait(.1)
        plane_0.turn_On_One_Light(2, "GREEN")
        plane_0.turn_Off_One_Light(3)
        wait(.1)
        
        plane_0.turn_On_One_Light(0, "BLUE")
        plane_0.turn_Off_One_Light(2)
        wait(.1)
        plane_0.turn_On_One_Light(1, "BLUE")
        plane_0.turn_Off_One_Light(0)
        wait(.1)
        plane_0.turn_On_One_Light(3, "BLUE")
        plane_0.turn_Off_One_Light(1)
        wait(.1)
        plane_0.turn_On_One_Light(2, "BLUE")
        plane_0.turn_Off_One_Light(3)
        wait(.1)
        
        
        
        
        GPIO.output(layer_zero_pin, HIGH)
        plane_0.turn_on_plane("GREEN")
        wait(1)
        GPIO.output(layer_zero_pin, LOW)
        GPIO.output(layer_one_pin, HIGH)
        plane_0.turn_on_plane("BLUE")
        wait(1)
        GPIO.output(layer_one_pin, LOW)
        GPIO.output(layer_two_pin, HIGH)
        plane_0.turn_on_plane("RED")
        wait(1)
        GPIO.output(layer_two_pin, LOW)
        GPIO.output(layer_three_pin, HIGH)
        plane_0.turn_on_plane("GREEN")
        wait(1)
        GPIO.output(layer_three_pin, LOW)